plugins {
    id 'com.android.application'
}

android {
    namespace 'se.steffy.facebookfirefox'
    compileSdk 35

    defaultConfig {
        applicationId "se.steffy.facebookfirefox"
        minSdk 23
        targetSdk 35
        versionCode 2
        versionName "1.1"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
