package se.linje11.gps;

import android.Manifest;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.database.Cursor;
import android.net.Uri;
import android.os.Bundle;
import android.provider.OpenableColumns;
import android.webkit.*;
import android.widget.*;
import androidx.appcompat.app.AppCompatActivity;
import org.json.*;
import java.io.*;
import java.nio.charset.StandardCharsets;

public class MainActivity extends AppCompatActivity {
 private static final int IMPORT_ROUTE=100, LOCATION_REQUEST=101;
 private final String[] days={"Måndag","Tisdag","Onsdag","Torsdag","Fredag"};
 private LinearLayout routeList; private Spinner daySpinner; private String selectedDay="Måndag"; private JSONObject pendingRoute;
 @Override protected void onCreate(Bundle b){super.onCreate(b);showMain();getWindow().addFlags(android.view.WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);}
 private void showMain(){setContentView(R.layout.activity_main);daySpinner=findViewById(R.id.daySpinner);routeList=findViewById(R.id.routeList);ArrayAdapter<String>a=new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,days);daySpinner.setAdapter(a);int pos=java.util.Arrays.asList(days).indexOf(selectedDay);daySpinner.setSelection(Math.max(0,pos));daySpinner.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onItemSelected(android.widget.AdapterView<?>p,android.view.View v,int pos,long id){selectedDay=days[pos];refresh();}public void onNothingSelected(android.widget.AdapterView<?>p){}});findViewById(R.id.btnImport).setOnClickListener(v->chooseFile());refresh();}
 private void chooseFile(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("application/json");startActivityForResult(i,IMPORT_ROUTE);}
 @Override protected void onActivityResult(int r,int c,Intent data){super.onActivityResult(r,c,data);if(r!=IMPORT_ROUTE||c!=RESULT_OK||data==null||data.getData()==null)return;try{Uri uri=data.getData();JSONObject root=new JSONObject(read(uri));if(!"gps-ruttinspelare".equals(root.optString("format"))){Toast.makeText(this,"Filen är inte en GPS Ruttinspelare-rutt",Toast.LENGTH_LONG).show();return;}String name=fileName(uri);if(name.endsWith(".json"))name=name.substring(0,name.length()-5);JSONArray routes=load(selectedDay);JSONObject item=new JSONObject();item.put("name",name);item.put("route",root);routes.put(item);save(selectedDay,routes);refresh();Toast.makeText(this,"Importerad till "+selectedDay,Toast.LENGTH_SHORT).show();}catch(Exception e){Toast.makeText(this,"Import misslyckades",Toast.LENGTH_LONG).show();}}
 private void refresh(){if(routeList==null)return;routeList.removeAllViews();JSONArray routes=load(selectedDay);if(routes.length()==0){TextView t=new TextView(this);t.setText("Inga rutter för "+selectedDay+" ännu.");t.setTextSize(17);t.setPadding(8,24,8,24);routeList.addView(t);return;}for(int i=0;i<routes.length();i++)try{JSONObject item=routes.getJSONObject(i),route=item.getJSONObject("route");JSONArray st=route.optJSONArray("stops");int stops=st==null?0:st.length();LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.VERTICAL);Button open=new Button(this);open.setAllCaps(false);open.setText(item.optString("name","Rutt "+(i+1))+"  •  "+stops+" stopp");final int idx=i;open.setOnClickListener(v->openRoute(idx));row.addView(open);Button del=new Button(this);del.setAllCaps(false);del.setText("Ta bort");del.setOnClickListener(v->deleteRoute(idx));row.addView(del);routeList.addView(row);}catch(Exception ignored){}}
 private void openRoute(int index){try{pendingRoute=load(selectedDay).getJSONObject(index).getJSONObject("route");if(android.os.Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.ACCESS_FINE_LOCATION,Manifest.permission.ACCESS_COARSE_LOCATION},LOCATION_REQUEST);else showMap(pendingRoute);}catch(Exception e){Toast.makeText(this,"Kunde inte öppna rutten",Toast.LENGTH_LONG).show();}}
 @Override public void onRequestPermissionsResult(int r,String[]p,int[]g){super.onRequestPermissionsResult(r,p,g);if(r==LOCATION_REQUEST&&pendingRoute!=null){if(g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED){try{showMap(pendingRoute);}catch(Exception e){Toast.makeText(this,"Kunde inte öppna kartan",Toast.LENGTH_LONG).show();}}else Toast.makeText(this,"GPS-behörighet behövs för kartan",Toast.LENGTH_LONG).show();}}
 private void showMap(JSONObject route)throws Exception{WebView web=new WebView(this);WebSettings s=web.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setGeolocationEnabled(true);web.setWebViewClient(new WebViewClient());web.setWebChromeClient(new WebChromeClient(){@Override public void onGeolocationPermissionsShowPrompt(String origin,GeolocationPermissions.Callback cb){cb.invoke(origin,true,false);}});web.loadDataWithBaseURL("https://linje11.local/",mapHtml(route),"text/html","UTF-8",null);setContentView(web);}
 private String mapHtml(JSONObject route)throws Exception{JSONArray points=route.optJSONArray("points"),stops=route.optJSONArray("stops");if(points==null||points.length()==0)throw new Exception("no points");StringBuilder p=new StringBuilder("[");for(int i=0;i<points.length();i++){JSONObject o=points.getJSONObject(i);if(i>0)p.append(',');p.append('[').append(o.getDouble("lat")).append(',').append(o.getDouble("lon")).append(']');}p.append(']');StringBuilder m=new StringBuilder("[");if(stops!=null)for(int i=0;i<stops.length();i++){JSONObject o=stops.getJSONObject(i);if(i>0)m.append(',');String label=o.optString("label",String.valueOf((char)('A'+i))).replace("'","\\'");m.append("{lat:").append(o.getDouble("lat")).append(",lon:").append(o.getDouble("lon")).append(",label:'").append(label).append("'}");}m.append(']');return "<!doctype html><html><head><meta name='viewport' content='width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no'><link rel='stylesheet' href='https://unpkg.com/leaflet@1.9.4/dist/leaflet.css'><style>html,body,#map{height:100%;margin:0}.stop{background:white;border:5px solid #e64a00;border-radius:50%;width:38px;height:38px;line-height:38px;text-align:center;font:bold 20px sans-serif;color:#d84300}.gps{background:#1687ff;border:4px solid white;border-radius:50%;width:20px;height:20px}</style></head><body><div id='map'></div><script src='https://unpkg.com/leaflet@1.9.4/dist/leaflet.js'></script><script>var pts="+p.toString()+",stops="+m.toString()+";var map=L.map('map');L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19}).addTo(map);var line=L.polyline(pts,{color:'#1976d2',weight:7}).addTo(map);map.fitBounds(line.getBounds(),{padding:[35,35]});stops.forEach(function(x){L.marker([x.lat,x.lon],{icon:L.divIcon({className:'',html:'<div class=\"stop\">'+x.label+'</div>',iconSize:[48,48],iconAnchor:[24,24]})}).addTo(map);});var gps=null;navigator.geolocation.watchPosition(function(pos){var ll=[pos.coords.latitude,pos.coords.longitude];if(!gps){gps=L.marker(ll,{icon:L.divIcon({className:'',html:'<div class=\"gps\"></div>',iconSize:[28,28],iconAnchor:[14,14]})}).addTo(map);}else{gps.setLatLng(ll);}map.panTo(ll);},function(){},{enableHighAccuracy:true,maximumAge:1000,timeout:10000});</script></body></html>";}
 @Override public void onBackPressed(){if(routeList==null||routeList.getParent()==null)showMain();else super.onBackPressed();}
 private void deleteRoute(int index){try{JSONArray old=load(selectedDay),n=new JSONArray();for(int i=0;i<old.length();i++)if(i!=index)n.put(old.get(i));save(selectedDay,n);refresh();}catch(Exception ignored){}}
 private JSONArray load(String day){try{return new JSONArray(getPreferences(MODE_PRIVATE).getString("routes_"+day,"[]"));}catch(Exception e){return new JSONArray();}}
 private void save(String day,JSONArray a){getPreferences(MODE_PRIVATE).edit().putString("routes_"+day,a.toString()).apply();}
 private String read(Uri u)throws Exception{InputStream in=getContentResolver().openInputStream(u);ByteArrayOutputStream out=new ByteArrayOutputStream();byte[]b=new byte[8192];int n;while((n=in.read(b))>0)out.write(b,0,n);in.close();return new String(out.toByteArray(),StandardCharsets.UTF_8);}
 private String fileName(Uri u){String name="Importerad rutt";Cursor c=getContentResolver().query(u,null,null,null,null);if(c!=null){if(c.moveToFirst()){int x=c.getColumnIndex(OpenableColumns.DISPLAY_NAME);if(x>=0)name=c.getString(x);}c.close();}return name;}
}
