plugins { id 'com.android.application' }

android {
    namespace 'se.minaarbetspass'
    compileSdk 35

    signingConfigs {
        release {
            def signingFile = file("mina-arbetspass.jks")
            if (signingFile.exists()) {
                storeFile signingFile
                storePassword "android"
                keyAlias "mina-arbetspass"
                keyPassword "android"
            }
        }
    }

    defaultConfig {
        applicationId "se.minaarbetspass"
        minSdk 23
        targetSdk 35
        versionCode 15
        versionName "1.13"
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

configurations.configureEach {
    exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib-jdk7'
    exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib-jdk8'
}

dependencies {
    implementation 'androidx.core:core:1.15.0'
    implementation 'com.google.mlkit:text-recognition:16.0.1'
    testImplementation 'junit:junit:4.13.2'
}
