plugins { id 'com.android.application' }

android {
    namespace 'se.minaarbetspass'
    compileSdk 35

    defaultConfig {
        applicationId "se.minaarbetspass"
        minSdk 23
        targetSdk 35
        versionCode 5
        versionName "1.4"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
