from pathlib import Path

exec(Path('scripts/version36.py').read_text(encoding='utf-8'))
main=Path('app/src/main/java/se/linje11/gps/MainActivity.java')
s=main.read_text(encoding='utf-8')

s=s.replace('import java.nio.charset.StandardCharsets;', '''import java.nio.charset.StandardCharsets;
import java.net.HttpURLConnection;
import java.net.URL;
import java.net.URLDecoder;
import java.net.URLEncoder;
import java.util.ArrayList;
import java.util.Locale;''',1)

# Add a second import button on the proven route chooser.
old='root.addView(imp,ilp);TextView hint=titleText("Håll inne på en rutt för att byta namn, namnge stopp eller ta bort.",13,false);'
new='root.addView(imp,ilp);Button gm=cleanButton("🗺 Importera Google Maps-länk",48);gm.setTextSize(16);gm.setOnClickListener(v->showGoogleMapsImport());LinearLayout.LayoutParams glp=new LinearLayout.LayoutParams(-1,dp(58));glp.setMargins(0,dp(4),0,0);root.addView(gm,glp);TextView hint=titleText("Håll inne på en rutt för att byta namn, namnge stopp eller ta bort.",13,false);'
if old not in s: raise SystemExit('v39 route chooser point not found')
s=s.replace(old,new,1)

anchor=' private void chooseFile(){'
if anchor not in s: raise SystemExit('v39 chooseFile point not found')
helper=r''' private static class GMPoint{double lat,lon;String name;GMPoint(double a,double b,String n){lat=a;lon=b;name=n;}}
 private void showGoogleMapsImport(){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(14),dp(6),dp(14),dp(6));EditText e=new EditText(this);e.setHint("Klistra in länken från Google Maps");e.setMinLines(2);box.addView(e);TextView h=new TextView(this);h.setText("Rutten sparas på "+selectedDay+". Start, mellanstopp och slut importeras.");h.setPadding(0,dp(8),0,0);box.addView(h);androidx.appcompat.app.AlertDialog d=new androidx.appcompat.app.AlertDialog.Builder(this).setTitle("Importera från Google Maps").setView(box).setNegativeButton("Avbryt",null).setPositiveButton("Importera",null).create();d.setOnShowListener(x->d.getButton(android.app.AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{String link=e.getText().toString().trim();if(link.isEmpty()){e.setError("Klistra in en Google Maps-länk");return;}d.dismiss();importGoogleMaps(link);}));d.show();}
 private void importGoogleMaps(String text){android.app.ProgressDialog pd=new android.app.ProgressDialog(this);pd.setMessage("Läser Google Maps-rutten…");pd.setCancelable(false);pd.show();new Thread(()->{try{String resolved=resolveGm(extractGmUrl(text));ArrayList<GMPoint> wp=parseGm(resolved);if(wp.size()<2)throw new Exception("Länken innehåller inte en komplett vägbeskrivning.");JSONObject route=routeFromGm(wp,resolved);String name="Google Maps • "+new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm",Locale.getDefault()).format(new java.util.Date());runOnUiThread(()->{pd.dismiss();try{JSONArray a=load(selectedDay);JSONObject item=new JSONObject();item.put("name",name);item.put("route",route);a.put(item);save(selectedDay,a);refresh();Toast.makeText(this,"Google Maps-rutten är importerad",Toast.LENGTH_LONG).show();}catch(Exception ex){Toast.makeText(this,"Kunde inte spara rutten",Toast.LENGTH_LONG).show();}});}catch(Exception ex){runOnUiThread(()->{pd.dismiss();new androidx.appcompat.app.AlertDialog.Builder(this).setTitle("Importen misslyckades").setMessage(ex.getMessage()).setPositiveButton("OK",null).show();});}}).start();}
 private String extractGmUrl(String text)throws Exception{java.util.regex.Matcher m=java.util.regex.Pattern.compile("https?://[^\\s]+",java.util.regex.Pattern.CASE_INSENSITIVE).matcher(text);if(!m.find())throw new Exception("Ingen Google Maps-länk hittades.");String u=m.group();while(u.endsWith(".")||u.endsWith(",")||u.endsWith(")"))u=u.substring(0,u.length()-1);return u;}
 private String resolveGm(String in)throws Exception{String cur=in;for(int i=0;i<8;i++){HttpURLConnection c=(HttpURLConnection)new URL(cur).openConnection();c.setInstanceFollowRedirects(false);c.setConnectTimeout(10000);c.setReadTimeout(10000);c.setRequestProperty("User-Agent","Mozilla/5.0 RuttGPS/39");int code=c.getResponseCode();String loc=c.getHeaderField("Location");c.disconnect();if(code>=300&&code<400&&loc!=null){cur=new URL(new URL(cur),loc).toString();continue;}break;}return cur;}
 private ArrayList<GMPoint> parseGm(String url)throws Exception{ArrayList<String> names=new ArrayList<>();Uri u=Uri.parse(url);String o=u.getQueryParameter("origin"),d=u.getQueryParameter("destination"),w=u.getQueryParameter("waypoints");if(d!=null){if(o!=null&&!o.trim().isEmpty())names.add(o);if(w!=null&&!w.trim().isEmpty())for(String x:w.split("\\|"))if(!x.trim().isEmpty())names.add(x);names.add(d);}else{String dec=URLDecoder.decode(url,"UTF-8");int ix=dec.indexOf("/maps/dir/");if(ix>=0){String tail=dec.substring(ix+10);int q=tail.indexOf('?');if(q>=0)tail=tail.substring(0,q);for(String x:tail.split("/")){String z=x.trim();if(z.isEmpty())continue;if(z.startsWith("@")||z.startsWith("data="))break;names.add(z.replace('+',' '));}}}ArrayList<GMPoint> out=new ArrayList<>();for(String n:names)out.add(geocodeGm(n));return out;}
 private GMPoint geocodeGm(String raw)throws Exception{String q0=raw.trim();java.util.regex.Matcher m=java.util.regex.Pattern.compile("^(-?\\d+(?:\\.\\d+)?)\\s*,\\s*(-?\\d+(?:\\.\\d+)?)$").matcher(q0);if(m.matches())return new GMPoint(Double.parseDouble(m.group(1)),Double.parseDouble(m.group(2)),q0);String q=URLEncoder.encode(q0,"UTF-8");JSONArray a=new JSONArray(httpGm("https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&countrycodes=se&q="+q));if(a.length()==0)a=new JSONArray(httpGm("https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&q="+q));if(a.length()==0)throw new Exception("Hittade inte platsen: "+q0);JSONObject z=a.getJSONObject(0);return new GMPoint(z.getDouble("lat"),z.getDouble("lon"),q0);}
 private String httpGm(String u)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(u).openConnection();c.setConnectTimeout(12000);c.setReadTimeout(20000);c.setRequestProperty("User-Agent","RuttGPS/39 Android");InputStream in=c.getInputStream();ByteArrayOutputStream out=new ByteArrayOutputStream();byte[]b=new byte[8192];int n;while((n=in.read(b))>0)out.write(b,0,n);in.close();c.disconnect();return new String(out.toByteArray(),StandardCharsets.UTF_8);}
 private JSONObject routeFromGm(ArrayList<GMPoint> w,String source)throws Exception{StringBuilder cs=new StringBuilder();for(int i=0;i<w.size();i++){if(i>0)cs.append(';');GMPoint p=w.get(i);cs.append(p.lon).append(',').append(p.lat);}JSONObject os=new JSONObject(httpGm("https://router.project-osrm.org/route/v1/driving/"+cs+"?overview=full&geometries=geojson&steps=false"));JSONArray rs=os.optJSONArray("routes");if(rs==null||rs.length()==0)throw new Exception("Kunde inte beräkna bilvägen.");JSONArray c=rs.getJSONObject(0).getJSONObject("geometry").getJSONArray("coordinates");JSONObject r=new JSONObject();r.put("format","gps-ruttinspelare");r.put("version",39);r.put("source","google-maps");r.put("source_url",source);JSONArray pts=new JSONArray();for(int i=0;i<c.length();i++){JSONArray x=c.getJSONArray(i);JSONObject p=new JSONObject();p.put("lat",x.getDouble(1));p.put("lon",x.getDouble(0));pts.put(p);}r.put("points",pts);GMPoint a=w.get(0),z=w.get(w.size()-1);JSONObject st=new JSONObject();st.put("lat",a.lat);st.put("lon",a.lon);st.put("label","START");st.put("name",a.name);r.put("start",st);JSONObject en=new JSONObject();en.put("lat",z.lat);en.put("lon",z.lon);en.put("label","SLUT");en.put("name",z.name);r.put("end",en);JSONArray stops=new JSONArray();for(int i=1;i<w.size()-1;i++){GMPoint p=w.get(i);JSONObject o=new JSONObject();o.put("lat",p.lat);o.put("lon",p.lon);o.put("label",String.valueOf((char)('A'+Math.min(i-1,25))));o.put("name",p.name);stops.put(o);}r.put("stops",stops);return r;}
'''
s=s.replace(anchor,helper+anchor,1)

s=s.replace('VERSION 36 • RUTTBIBLIOTEK','VERSION 39 • GOOGLE MAPS-IMPORT')
s=s.replace('VERSION 36 • "+selectedDay.toUpperCase()','VERSION 39 • "+selectedDay.toUpperCase()')
main.write_text(s,encoding='utf-8')

b=Path('app/build.gradle');t=b.read_text(encoding='utf-8').replace('versionCode 36','versionCode 39').replace('versionName "36.0"','versionName "39.0"');b.write_text(t,encoding='utf-8')
print('Version 39 applied: Google Maps link import into selected weekday route library')
