from pathlib import Path

exec(Path('scripts/version71.py').read_text(encoding='utf-8'))

main=Path('app/src/main/java/se/linje11/gps/MainActivity.java')
s=main.read_text(encoding='utf-8')

s=s.replace('VERSION 71 •','VERSION 72 •')

# Preserve the meaningful name generated by Recorder/Editor instead of always
# calling incoming routes "Redigerad rutt".
old='''   JSONObject item=new JSONObject();
   item.put("name","Redigerad rutt");
   item.put("route",root);'''
new='''   JSONObject item=new JSONObject();
   String incomingName=root.optString("routeName","Redigerad rutt").trim();
   if(incomingName.isEmpty())incomingName="Redigerad rutt";
   item.put("name",incomingName);
   item.put("route",root);'''
if old not in s: raise SystemExit('v72 incoming name anchor missing')
s=s.replace(old,new,1)

# Keep the previous saved route list as a safety snapshot before every write.
old=''' private void save(String day,JSONArray a){getPreferences(MODE_PRIVATE).edit().putString("routes_"+day,a.toString()).apply();}'''
new=''' private void save(String day,JSONArray a){android.content.SharedPreferences p=getPreferences(MODE_PRIVATE);String key="routes_"+day;String old=p.getString(key,"[]");p.edit().putString("backup_"+key,old).putString(key,a.toString()).putLong("backup_time_"+day,System.currentTimeMillis()).apply();}'''
if old not in s: raise SystemExit('v72 save anchor missing')
s=s.replace(old,new,1)

# Protect against accidental route deletion.
old=''' private void deleteRoute(int index){try{JSONArray old=load(selectedDay),n=new JSONArray();for(int i=0;i<old.length();i++)if(i!=index)n.put(old.get(i));save(selectedDay,n);refresh();}catch(Exception ignored){}}'''
new=''' private void deleteRoute(int index){new android.app.AlertDialog.Builder(this).setTitle("Ta bort rutten?").setMessage("Rutten kan tas bort från "+selectedDay+". En säkerhetskopia av föregående lista sparas automatiskt.").setNegativeButton("Avbryt",null).setPositiveButton("Ta bort",(d,w)->{try{JSONArray old=load(selectedDay),n=new JSONArray();for(int i=0;i<old.length();i++)if(i!=index)n.put(old.get(i));save(selectedDay,n);refresh();Toast.makeText(this,"Rutten borttagen",Toast.LENGTH_SHORT).show();}catch(Exception ignored){}}).show();}'''
if old not in s: raise SystemExit('v72 delete anchor missing')
s=s.replace(old,new,1)

main.write_text(s,encoding='utf-8')

b=Path('app/build.gradle')
t=b.read_text(encoding='utf-8').replace('versionCode 71','versionCode 72').replace('versionName "71.0"','versionName "72.0"')
b.write_text(t,encoding='utf-8')
print('Version 72 applied: named incoming routes, backup-before-save and delete confirmation')
