from pathlib import Path

exec(Path('scripts/version36.py').read_text(encoding='utf-8'))
main=Path('app/src/main/java/se/linje11/gps/MainActivity.java')
s=main.read_text(encoding='utf-8')

s=s.replace('import java.nio.charset.StandardCharsets;', '''import java.nio.charset.StandardCharsets;
import java.net.HttpURLConnection;
import java.net.URL;
import java.net.URLDecoder;
import java.net.URLEncoder;
import java.util.ArrayList;
import java.util.Locale;''',1)

# Open shared Google Maps links after the normal weekday chooser exists.
old='@Override protected void onCreate(Bundle b){super.onCreate(b);getWindow().addFlags(android.view.WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);showDayChooser();}'
new='''@Override protected void onCreate(Bundle b){super.onCreate(b);getWindow().addFlags(android.view.WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);showDayChooser();handleSharedGoogleMaps(getIntent());}
 @Override protected void onNewIntent(Intent i){super.onNewIntent(i);setIntent(i);showDayChooser();handleSharedGoogleMaps(i);}'''
if old not in s: raise SystemExit('v38 onCreate point not found')
s=s.replace(old,new,1)

# Add a Google Maps import button below the existing JSON import button.
old='''root.addView(imp,ilp);TextView hint=titleText("Håll inne på en rutt för att byta namn, namnge stopp eller ta bort.",13,false);'''
new='''root.addView(imp,ilp);Button gm=cleanButton("🗺 Importera från Google Maps",48);gm.setTextSize(16);gm.setOnClickListener(v->showGoogleMapsPasteDialog(null));LinearLayout.LayoutParams glp=new LinearLayout.LayoutParams(-1,dp(58));glp.setMargins(0,dp(4),0,0);root.addView(gm,glp);TextView hint=titleText("Håll inne på en rutt för att byta namn, namnge stopp eller ta bort.",13,false);'''
if old not in s: raise SystemExit('v38 route chooser import point not found')
s=s.replace(old,new,1)

anchor=' private void chooseFile(){'
if anchor not in s: raise SystemExit('v38 chooseFile point not found')
helper=r''' private static class GPoint{double lat,lon;String name;GPoint(double a,double b,String n){lat=a;lon=b;name=n;}}
 private static class GRoute{final ArrayList<GPoint> points=new ArrayList<>();String sourceUrl;}
 private void handleSharedGoogleMaps(Intent i){if(i==null||!Intent.ACTION_SEND.equals(i.getAction()))return;String t=i.getStringExtra(Intent.EXTRA_TEXT);if(t!=null&&(t.contains("google.")||t.contains("goo.gl")||t.contains("maps.app")))showGoogleMapsPasteDialog(t);}
 private void showGoogleMapsPasteDialog(String preset){final LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);int p=dp(14);box.setPadding(p,p/2,p,p/2);final EditText input=new EditText(this);input.setHint("Klistra in Google Maps-länk");input.setMinLines(2);if(preset!=null)input.setText(preset);box.addView(input);TextView l=new TextView(this);l.setText("Spara rutten på dag:");l.setPadding(0,dp(8),0,0);box.addView(l);final Spinner sp=new Spinner(this);sp.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,days));int pos=java.util.Arrays.asList(days).indexOf(selectedDay);sp.setSelection(Math.max(0,pos));box.addView(sp);final androidx.appcompat.app.AlertDialog d=new androidx.appcompat.app.AlertDialog.Builder(this).setTitle("Importera från Google Maps").setView(box).setNegativeButton("Avbryt",null).setPositiveButton("Importera",null).create();d.setOnShowListener(x->d.getButton(android.app.AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{String link=input.getText().toString().trim();if(link.isEmpty()){input.setError("Klistra in en Google Maps-länk");return;}String day=days[sp.getSelectedItemPosition()];d.dismiss();importGoogleMapsRoute(link,day);}));d.show();}
 private void importGoogleMapsRoute(String text,String day){final android.app.ProgressDialog pd=new android.app.ProgressDialog(this);pd.setMessage("Importerar Google Maps-rutt…");pd.setCancelable(false);pd.show();new Thread(()->{try{String link=extractGoogleMapsUrl(text),resolved=resolveRedirects(link);GRoute g=parseGoogleRoute(resolved);JSONObject route=buildImportedRoute(g);String name="Google Maps • "+new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm",Locale.getDefault()).format(new java.util.Date());runOnUiThread(()->{pd.dismiss();try{JSONArray routes=load(day);JSONObject item=new JSONObject();item.put("name",name);item.put("route",route);routes.put(item);save(day,routes);selectedDay=day;showRouteChooser();Toast.makeText(this,"Google Maps-rutten importerades till "+day,Toast.LENGTH_LONG).show();}catch(Exception e){Toast.makeText(this,"Kunde inte spara rutten",Toast.LENGTH_LONG).show();}});}catch(Exception e){runOnUiThread(()->{pd.dismiss();new androidx.appcompat.app.AlertDialog.Builder(this).setTitle("Importen misslyckades").setMessage(e.getMessage()==null?"Kunde inte läsa Google Maps-rutten.":e.getMessage()).setPositiveButton("OK",null).show();});}}).start();}
 private String extractGoogleMapsUrl(String text)throws Exception{java.util.regex.Matcher m=java.util.regex.Pattern.compile("https?://[^\\s]+",java.util.regex.Pattern.CASE_INSENSITIVE).matcher(text);if(!m.find())throw new Exception("Ingen webblänk hittades.");String u=m.group();while(u.endsWith(")")||u.endsWith(".")||u.endsWith(","))u=u.substring(0,u.length()-1);return u;}
 private String resolveRedirects(String input)throws Exception{String cur=input;for(int i=0;i<8;i++){HttpURLConnection c=(HttpURLConnection)new URL(cur).openConnection();c.setInstanceFollowRedirects(false);c.setConnectTimeout(10000);c.setReadTimeout(10000);c.setRequestProperty("User-Agent","Mozilla/5.0 RuttGPS/38");int code=c.getResponseCode();String loc=c.getHeaderField("Location");c.disconnect();if(code>=300&&code<400&&loc!=null){cur=new URL(new URL(cur),loc).toString();continue;}break;}return cur;}
 private GRoute parseGoogleRoute(String url)throws Exception{GRoute out=new GRoute();out.sourceUrl=url;Uri u=Uri.parse(url);ArrayList<String> names=new ArrayList<>();String origin=u.getQueryParameter("origin"),dest=u.getQueryParameter("destination"),way=u.getQueryParameter("waypoints");if(dest!=null){if(origin!=null&&!origin.trim().isEmpty())names.add(origin);else{GPoint p=getLastKnownPoint();if(p!=null)out.points.add(p);}if(way!=null&&!way.trim().isEmpty())for(String w:way.split("\\|"))if(!w.trim().isEmpty())names.add(w);names.add(dest);}else{String dec=URLDecoder.decode(url,"UTF-8");int di=dec.indexOf("/maps/dir/");if(di>=0){String tail=dec.substring(di+10);int q=tail.indexOf('?');if(q>=0)tail=tail.substring(0,q);for(String x:tail.split("/")){String z=x.trim();if(z.isEmpty())continue;if(z.startsWith("@")||z.startsWith("data=")||z.startsWith("data!"))break;names.add(z.replace('+',' '));}}}for(String n:names)out.points.add(resolvePlace(n));if(out.points.size()<2)throw new Exception("Länken saknar en komplett rutt. Dela vägbeskrivningen från Google Maps med start och destination.");return out;}
 private GPoint getLastKnownPoint(){try{if(android.os.Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED)return null;android.location.LocationManager lm=(android.location.LocationManager)getSystemService(LOCATION_SERVICE);android.location.Location best=null;for(String p:lm.getProviders(true)){android.location.Location l=lm.getLastKnownLocation(p);if(l!=null&&(best==null||l.getTime()>best.getTime()))best=l;}return best==null?null:new GPoint(best.getLatitude(),best.getLongitude(),"Min plats");}catch(Exception e){return null;}}
 private GPoint resolvePlace(String raw)throws Exception{String q0=raw.trim();java.util.regex.Matcher m=java.util.regex.Pattern.compile("^\\s*(-?\\d+(?:\\.\\d+)?)\\s*,\\s*(-?\\d+(?:\\.\\d+)?)\\s*$").matcher(q0);if(m.matches())return new GPoint(Double.parseDouble(m.group(1)),Double.parseDouble(m.group(2)),q0);String q=URLEncoder.encode(q0,"UTF-8");String js=httpGet("https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&countrycodes=se&q="+q);JSONArray a=new JSONArray(js);if(a.length()==0){js=httpGet("https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&q="+q);a=new JSONArray(js);}if(a.length()==0)throw new Exception("Hittade inte platsen: "+q0);JSONObject o=a.getJSONObject(0);return new GPoint(o.getDouble("lat"),o.getDouble("lon"),q0);}
 private String httpGet(String url)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(url).openConnection();c.setConnectTimeout(12000);c.setReadTimeout(20000);c.setRequestProperty("User-Agent","RuttGPS/38 Android route importer");InputStream in=c.getInputStream();ByteArrayOutputStream out=new ByteArrayOutputStream();byte[]b=new byte[8192];int n;while((n=in.read(b))>0)out.write(b,0,n);in.close();c.disconnect();return new String(out.toByteArray(),StandardCharsets.UTF_8);}
 private JSONObject buildImportedRoute(GRoute g)throws Exception{StringBuilder cs=new StringBuilder();for(int i=0;i<g.points.size();i++){if(i>0)cs.append(';');GPoint p=g.points.get(i);cs.append(p.lon).append(',').append(p.lat);}JSONObject rr=new JSONObject(httpGet("https://router.project-osrm.org/route/v1/driving/"+cs+"?overview=full&geometries=geojson&steps=false"));JSONArray routes=rr.optJSONArray("routes");if(routes==null||routes.length()==0)throw new Exception("Kunde inte beräkna körvägen mellan stoppen.");JSONArray coords=routes.getJSONObject(0).getJSONObject("geometry").getJSONArray("coordinates");JSONObject root=new JSONObject();root.put("format","gps-ruttinspelare");root.put("version",38);root.put("source","google-maps");root.put("source_url",g.sourceUrl);JSONArray pts=new JSONArray();for(int i=0;i<coords.length();i++){JSONArray c=coords.getJSONArray(i);JSONObject p=new JSONObject();p.put("lat",c.getDouble(1));p.put("lon",c.getDouble(0));pts.put(p);}root.put("points",pts);GPoint first=g.points.get(0),last=g.points.get(g.points.size()-1);JSONObject st=new JSONObject();st.put("label","START");st.put("lat",first.lat);st.put("lon",first.lon);st.put("name",first.name);root.put("start",st);JSONObject en=new JSONObject();en.put("label","SLUT");en.put("lat",last.lat);en.put("lon",last.lon);en.put("name",last.name);root.put("end",en);JSONArray stops=new JSONArray();for(int i=1;i<g.points.size()-1;i++){GPoint p=g.points.get(i);JSONObject o=new JSONObject();o.put("label",String.valueOf((char)('A'+Math.min(i-1,25))));o.put("lat",p.lat);o.put("lon",p.lon);o.put("name",p.name);stops.put(o);}root.put("stops",stops);return root;}
'''
s=s.replace(anchor,helper+anchor,1)

s=s.replace('VERSION 36 • RUTTBIBLIOTEK','VERSION 38 • GOOGLE MAPS-IMPORT')
s=s.replace('VERSION 36 • "+selectedDay.toUpperCase()','VERSION 38 • "+selectedDay.toUpperCase()')
main.write_text(s,encoding='utf-8')

manifest=Path('app/src/main/AndroidManifest.xml');m=manifest.read_text(encoding='utf-8')
needle='''            <intent-filter>\n                <action android:name="android.intent.action.MAIN" />\n                <category android:name="android.intent.category.LAUNCHER" />\n            </intent-filter>'''
share=needle+'''\n            <intent-filter>\n                <action android:name="android.intent.action.SEND" />\n                <category android:name="android.intent.category.DEFAULT" />\n                <data android:mimeType="text/plain" />\n            </intent-filter>'''
if needle not in m: raise SystemExit('v38 manifest point not found')
m=m.replace(needle,share,1);manifest.write_text(m,encoding='utf-8')

b=Path('app/build.gradle');t=b.read_text(encoding='utf-8').replace('versionCode 36','versionCode 38').replace('versionName "36.0"','versionName "38.0"');b.write_text(t,encoding='utf-8')
print('Version 38 applied: Google Maps share/paste import with day selection and road routing')
