from pathlib import Path
exec(Path('scripts/version16.py').read_text(encoding='utf-8'))
p=Path('app/src/main/java/se/linje11/gps/MainActivity.java')
s=p.read_text(encoding='utf-8')

# Version 17: safer driving view. Keep the proven v16 route/entrance logic,
# add a directional vehicle marker, stronger stop markers, smarter arrival,
# and forward-looking map framing without depending on map rotation plugins.

# Directional vehicle marker that can rotate with GPS heading.
old="var gps=null,acc=null,lastGps=null,follow=true,phase=start?'start':'route',idx=parseInt(localStorage.getItem('rutt_idx')||'0'),lastRoad=0,roadKm=null,roadSec=null,nextTurn=null,nearHits=0,lastSpoken='',lastHeading=null,activeLine=L.polyline([],{color:'#d32f2f',weight:9,opacity:.88}).addTo(map);if(idx<0||idx>stops.length)idx=0;"
new="var gps=null,acc=null,lastGps=null,follow=true,phase=start?'start':'route',idx=parseInt(localStorage.getItem('rutt_idx')||'0'),lastRoad=0,roadKm=null,roadSec=null,nextTurn=null,nearHits=0,lastSpoken='',lastHeading=null,vehicle=null,activeLine=L.polyline([],{color:'#d32f2f',weight:9,opacity:.88}).addTo(map);if(idx<0||idx>stops.length)idx=0;function vehicleIcon(h){return L.divIcon({className:'',iconSize:[42,42],iconAnchor:[21,21],html:'<div style=\"font-size:34px;line-height:42px;text-align:center;transform:rotate('+(h||0)+'deg);filter:drop-shadow(0 2px 2px #555)\">⬆️</div>'});}"
if old not in s: raise SystemExit('v17 state point not found')
s=s.replace(old,new,1)

# Update directional vehicle and place GPS lower in the viewport by panning
# a little ahead in the current heading direction.
needle="lastGps=[pos.coords.latitude,pos.coords.longitude];lastHeading=(typeof pos.coords.heading==='number'&&!isNaN(pos.coords.heading))?pos.coords.heading:lastHeading;"
repl=needle+"if(!vehicle){vehicle=L.marker(lastGps,{icon:vehicleIcon(lastHeading)}).addTo(map);}else{vehicle.setLatLng(lastGps);vehicle.setIcon(vehicleIcon(lastHeading));}"
s=s.replace(needle,repl,1)
oldzoom="if(follow){var sp=(pos.coords.speed||0)*3.6;var z=sp>70?14:sp>35?15:16;map.setView(lastGps,z);}"
newzoom="if(follow){var sp=(pos.coords.speed||0)*3.6;var z=sp>70?14:sp>35?15:16;var c=lastGps;if(lastHeading!=null&&sp>5){var rad=lastHeading*Math.PI/180,lead=sp>70?.012:sp>35?.007:.0035;c=[lastGps[0]+Math.cos(rad)*lead,lastGps[1]+Math.sin(rad)*lead/Math.max(.25,Math.cos(lastGps[0]*Math.PI/180))];}map.setView(c,z);}"
if oldzoom in s: s=s.replace(oldzoom,newzoom,1)

# Arrival requires repeated proximity hits. v16 already measures against the
# driveable entrance; increase stability before automatically advancing.
s=s.replace("if(d<45)nearHits++;else nearHits=0;","if(d<40)nearHits++;else if(d>65)nearHits=0;")
s=s.replace("if(nearHits>=2){","if(nearHits>=3){")

# Make route stop markers more prominent if their existing labels are A/B/C.
# CSS is injected into the HTML generated by the Java source.
css=".stop-pin{background:#ffca28;color:#111;border:4px solid #fff;border-radius:50%;width:38px;height:38px;line-height:30px;text-align:center;font-weight:900;font-size:20px;box-shadow:0 2px 5px #555}.stop-pin.next{background:#ff5722;color:#fff;transform:scale(1.18)}"
s=s.replace("</style>",css+"</style>",1)

# Clearer status wording for driving.
s=s.replace("' • 🚗 Till infart ✓'","' • 🚗 Till infart ✓ • AUTO'")

s=s.replace('VERSION 16 • RUTTBIBLIOTEK','VERSION 17 • RUTTBIBLIOTEK').replace('VERSION 16 • \"+selectedDay.toUpperCase()','VERSION 17 • \"+selectedDay.toUpperCase()')
p.write_text(s,encoding='utf-8')

b=Path('app/build.gradle')
t=b.read_text(encoding='utf-8').replace('versionCode 16','versionCode 17').replace('versionName \"16.0\"','versionName \"17.0\"')
b.write_text(t,encoding='utf-8')
